project="doit-ticket-review"
region="us-central1"
multi_region="US"
app_name="ticket-review"
brand_name="874764407517"
sql_file = "sample_tickets.sql.tftpl"
sampled_data_dataset_id = "sampled_data"
vertex_model_dataset_id = "vertex_models"